Competition Link: https://www.kaggle.com/competitions/store-sales-time-series-forecasting/data

The training data, comprising time series of features store_nbr, family, and onpromotion as well as the target sales.
1. `store_nbr` identifies the store at which the products are sold.
2. `family` identifies the type of product sold.
3. `sales` gives the total sales for a product family at a particular store at a given date. Fractional values are possible since products can be sold in fractional units (1.5 kg of cheese, for instance, as opposed to 1 bag of chips).
5. `onpromotion` gives the total number of items in a product family that were being promoted at a store at a given date

Import modules

In [13]:
import kaggle
import pandas as pd
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

Uncomment the cell below if you don't have the datasets yet

In [5]:
# !kaggle competitions download -c store-sales-time-series-forecasting
# !unzip store-sales-time-series-forecasting.zip

In [6]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [7]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

In [8]:
train_df[train_df['sales'] != 0]

,id,date,store_nbr,family,sales,onpromotion
563,563,2013-01-01,25,BEAUTY,2.000,0
564,564,2013-01-01,25,BEVERAGES,810.000,0
566,566,2013-01-01,25,BREAD/BAKERY,180.589,0
568,568,2013-01-01,25,CLEANING,186.000,0
569,569,2013-01-01,25,DAIRY,143.000,0
...,...,...,...,...,...,...
3000883,3000883,2017-08-15,9,POULTRY,438.133,0
3000884,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
3000885,3000885,2017-08-15,9,PRODUCE,2419.729,148
3000886,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
3000887,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [12]:
train_df[train_df['store_nbr'] == 23]

,id,date,store_nbr,family,sales,onpromotion
495,495,2013-01-01,23,AUTOMOTIVE,0.000,0
496,496,2013-01-01,23,BABY CARE,0.000,0
497,497,2013-01-01,23,BEAUTY,0.000,0
498,498,2013-01-01,23,BEVERAGES,0.000,0
499,499,2013-01-01,23,BOOKS,0.000,0
...,...,...,...,...,...,...
2999629,2999629,2017-08-15,23,POULTRY,439.349,0
2999630,2999630,2017-08-15,23,PREPARED FOODS,22.795,0
2999631,2999631,2017-08-15,23,PRODUCE,1156.310,7
2999632,2999632,2017-08-15,23,SCHOOL AND OFFICE SUPPLIES,0.000,0
2999633,2999633,2017-08-15,23,SEAFOOD,2.000,0

Feature Engineering

In [ ]:
def feature_engineer(df):
    # Datetime conversion
    df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
    
    # OneHot Encoder for family feature
    
    return df

In [15]:
feature_engineer(train_df)

0

In [17]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         datetime64[ns]
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 137.4+ MB